export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
};

export default function AuthLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>
                {children}
                <footer
                    style={{
                        backgroundColor: "#9db3c8",
                        padding: "1rem",
                    }}>
                    <p>Footer</p>
                </footer>
            </body>
        </html>
    );
}
