import Link from "next/link";

const navLinks = [
    { name: "Register", href: "/register" },
    { name: "Login", href: "/login" },
    { name: "Forgot Password", href: "/forgot-password" },
];

export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
};

export default function AuthLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <div>
            {navLinks.map((link) => {
                return (
                    <Link href={link.href} key={link.name}>
                        {link.name}
                    </Link>
                );
            })}
            {children}
        </div>
    );
}
//  <header
//                     style={{
//                         backgroundColor: "aqua",
//                         padding: "1rem",
//                     }}>
//                     <p>This is header for auth</p>
{
    /* </header> */
}
//    <footer
//     style={{
//         backgroundColor: "yellowgreen",
//         padding: "1rem",
//     }}>
//     <p>Footer for auth</p>
// </footer>
