export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <h3
                style={{
                    backgroundColor: "lightblue",
                    padding: "1rem",
                }}>
                Something about goods
            </h3>
            <body>{children}</body>
        </html>
    );
}
