export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>
                <header
                    style={{
                        backgroundColor: "#FFE4C4",
                        padding: "1rem",
                    }}>
                    <p>This is header</p>
                </header>
                {children}
                <footer
                    style={{
                        backgroundColor: "#8A2BE2",
                        padding: "1.5rem 1rem 3rem",
                    }}>
                    <p>Footer</p>
                </footer>
            </body>
        </html>
    );
}
