export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>
                <header
                    style={{
                        backgroundColor: "#DC143C",
                        padding: "2rem 0.5rem",
                    }}>
                    <p>This is header</p>
                </header>
                {children}
                <footer
                    style={{
                        backgroundColor: "#FF7F50",
                        padding: "0.5rem 1rem 2rem",
                    }}>
                    <p>Footer is shere</p>
                </footer>
            </body>
        </html>
    );
}
