export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>
                <div
                    style={{
                        backgroundColor: "Yellow",
                        padding: "1rem",
                    }}>
                    <p
                        style={{
                            color: "blue",
                            fontWeight: "bold",
                        }}>
                        Lorem ipsum dolor sit amet consectetur adipisicing elit.
                        Officiis voluptatem quas quaerat!
                    </p>
                </div>

                {children}
            </body>
        </html>
    );
}
