export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <>
            <header
                style={{
                    backgroundColor: "green",
                    padding: "1rem",
                }}>
                <p>I am header for Product List</p>
            </header>
            {children}
        </>
    );
}
