export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
};

export default function MarketingLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>
                <header
                    style={{
                        backgroundColor: "Violet",
                        padding: "1rem",
                    }}>
                    <p>Header for market</p>
                </header>
                {children}
                <footer
                    style={{
                        backgroundColor: "Yellow",
                        padding: "1rem",
                    }}>
                    <p>Footer for market</p>
                </footer>
            </body>
        </html>
    );
}
