export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
};

export default function MarketingLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <header
                style={{
                    backgroundColor: "lightblue",
                    padding: "1rem",
                }}>
                <p>Header</p>
            </header>
            <body>
                {children}
                <footer
                    style={{
                        backgroundColor: "Green",
                        padding: "1rem",
                    }}>
                    <p>Footer</p>
                </footer>
            </body>
        </html>
    );
}
